config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[new create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  get '/logout' => 'sessions#destroy'
  get '/login' => 'sessions#new'
  post '/signup' => 'sessions#create'
  resources :advertisments
  get 'home' => 'index#home'
  get 'gallery' => 'index#gallery'
  get 'contacts' => 'index#contacts'
  get 'competition' => 'competition#competition'
  root 'index#home'
end

app/models/advertisment.rb
# frozen_string_literal: true

class Advertisment < ActiveRecord::Base
  validates :name, length: { minimum: 2 }
  validates :description, length: { maximum: 1500 }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  validates :name, length: { minimum: 5 }
end

app/controllers/advertisments_controller.rb
# frozen_string_literal: true

class AdvertismentsController < ApplicationController
  def index
    @advertisment = Advertisment.all
  end

  def new
    @advertisment = Advertisment.new
  end

  def show
    @advertisment = Advertisment.find(params[:id])
  end

  def create
    advertisment = Advertisment.create(advertisment_params)
    redirect_to advertisments_path
  end

  def edit
    @advertisment = Advertisment.find(params[:id])
  end

  def update
    @advertisment = Advertisment.find(params[:id])
    if @advertisment.update(advertisment_params)
      redirect_to advertisments_path
    else
      render :endit
    end
  end

  def destroy
    @advertisment = Advertisment.find(params[:id])
    @advertisment.destroy
    redirect_to advertisments_path
  end

  private

  def advertisment_params
    params.require(:advertisment).permit(:name, :description)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?
  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end
end

app/controllers/competition_controller.rb
# frozen_string_literal: true

class CompetitionController < ActionController::Base
  def competition; end
end

app/controllers/index_controller.rb
# frozen_string_literal: true

class IndexController < ActionController::Base
  def home; end

  def contacts; end

  def gallery; end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authorized,
                     only: %i[new create welcome]
  def new; end

  def login; end

  def create
    @user = User.find_by(username: params[:username])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/advertisments/'
    else
      redirect_to '/welcome'
    end
  end

  def page_requires_login; end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :authorized,
                     only: %i[new create]
  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username, :password))
    session[:user_id] = @user.id
    redirect_to '/advertisments/'
  end
end

app/helpers/advertisment_helper.rb
# frozen_string_literal: true

module AdvertismentHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/advertisments/edit.html.erb
<%= form_for @advertisment do |f| %>

<div>
    <%= f.label :name %>
    <%= f.text_field :name %>
</div>

<div>
    <%= f.label :description %>
    <%= f.text_field :description %>
</div>


<div>
    <%= f.submit%>
</div>

<% end %>

app/views/advertisments/index.html.erb
<head>
            <%= stylesheet_link_tag 'advIndex',  :media => "all" %>
</head>

<button><%= link_to "sukurti posta", new_advertisment_path%></button>
<div class="main">
 
<% @advertisment.each do |ad| %>

<div class="center">
  <div class="property-card">
    <a href="#">
      <div class="property-image">
        <div class="property-image-title">
        </div>
      </div></a>
    <div class="property-description">
      <h5> <%= ad.name%> </h5>
      <p><%= ad.description%></td></p>
    </div>
    <a href="#">
      <div class="property-social-icons">
      <button><%= link_to "Delete", ad, method: :delete, data: {confirm: "are you sure you want to del?"} %></button>
      </div>
    </a>
  </div>
</div>




<% end %>

</div>
</div>

app/views/advertisments/new.html.erb
<style>
  body{
    width: 100vw;
    height: 100vh;
  }
  .back {
    display: flex;
    width: 100%;
    height: 100%;
    justify-content: center;
    align-items: center;
    position: absolute;
    top: 0;
    left: 0;
  }
</style>
<div class="back">
<div> 
<h3>Create blog post</h3>
<%= form_with model: @advertisment do |form| %>
<div>
<div class="form-outline">
   <%= form.text_field :name, placeholder: "name" %>
  <label class="form-label" for="formControlLg">Title</label>
</div>
 <div class="form-outline">
  <%= form.text_field :description, placeholder: "Description" %>
  <label class="form-label" for="formControlLg">Description</label>
</div>
  </div>
  <button> <%= form.submit %> </button>
</div>
</div>

<% end %>

app/views/advertisments/show.html.erb
<h1><%= @advertisment.name %></h1>
<h4>"<%= @advertisment.description %>"</h4>
<%= link_to 'Remove', @advertisment, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/competition/competition.html.erb
<head>
            <%= stylesheet_link_tag 'Competition','layout',  :media => "all" %>
</head>

<body>
  <header>Lietuvos Motokroso Sporto Federacija</header>


    <nav class="Navigation"> 
        <a href="home.html"> Main</a>
        <a href="contacts.html"> Contacts</a> 
        <a href="gallery.html"> Gallery</a>
        <a href="competition.html"> Competition</a>
    </nav>

    <div class="container">

<div class="row">
  <div class="column">
      <div class="text">2020m. varžybų dalyvių galutinė lentelė</div>

  </div>
  <div class="column">
    <div class="compTable">
      <h2>Competition Leaderboards 2020</h2>
      <table>
        <tr>
          <th>Firstname</th>
          <th>Lastname</th>
          <th>Points</th>
          <th>Position</th>
        </tr>
        <tr class="extra" >
          <td>Ernestas</td>
          <td>Liepis</td>
          <td>222</td>
          <td >1</td>
        </tr>
        <tr>
          <td>Arminas</td>
          <td>Venclovas</td>
          <td>180</td>
          <td>2</td>
        </tr>
        <tr>
          <td>Norbertas</td>
          <td>Žėkas</td>
          <td>174</td>
          <td>3</td>
        </tr>
        <tr>
          <td>Kevinas</td>
          <td>Zaksas</td>
          <td>144</td>
          <td>4</td>
       </tr>
       <tr>
          <td>Adamas</td>
          <td>Čekavičius</td>
          <td>127</td>
          <td>5</td>
        </tr>
        <tr>
          <td>Radvilas</td>
          <td>Žaltauskas</td>
          <td>91</td>
          <td>6</td>
        </tr>
        <tr>
          <td>Donatas</td>
          <td>Aleksa</td>
          <td>84</td>
          <td>7</td>
        </tr>
        <tr>
          <td>Savelijs</td>
          <td>Sjomins</td>
          <td>50</td>
          <td>8</td>
        </tr>
        <tr>
          <td>Jonas</td>
          <td>Petraitis</td>
          <td>48</td>
          <td>9</td>
        </tr>
        <tr>
          <td>Peteris</td>
          <td>Cerinš</td>
          <td>34</td>
          <td>10</td>
        </tr>
      </table>

  </div>

</div>




</div>
    
<div class="row">
  <div class="column">
      <div class="text">2019m. varžybų dalyvių galutinė lentelė</div>

  </div>
  <div class="column">
    <div class="compTable">
      <h2>Competition Leaderboards 2019</h2>
      <table>
        <tr>
          <th>Firstname</th>
          <th>Lastname</th>
          <th>Points</th>
          <th>Position</th>
        </tr>
        <tr class="extra" >
          <td>Ernestas</td>
          <td>Liepis</td>
          <td>222</td>
          <td >1</td>
        </tr>
        <tr>
          <td>Arminas</td>
          <td>Venclovas</td>
          <td>180</td>
          <td>2</td>
        </tr>
        <tr>
          <td>Norbertas</td>
          <td>Žėkas</td>
          <td>174</td>
          <td>3</td>
        </tr>
        <tr>
          <td>Kevinas</td>
          <td>Zaksas</td>
          <td>144</td>
          <td>4</td>
       </tr>
       <tr>
          <td>Adamas</td>
          <td>Čekavičius</td>
          <td>127</td>
          <td>5</td>
        </tr>
        <tr>
          <td>Radvilas</td>
          <td>Žaltauskas</td>
          <td>91</td>
          <td>6</td>
        </tr>
        <tr>
          <td>Donatas</td>
          <td>Aleksa</td>
          <td>84</td>
          <td>7</td>
        </tr>
        <tr>
          <td>Savelijs</td>
          <td>Sjomins</td>
          <td>50</td>
          <td>8</td>
        </tr>
        <tr>
          <td>Jonas</td>
          <td>Petraitis</td>
          <td>48</td>
          <td>9</td>
        </tr>
        <tr>
          <td>Peteris</td>
          <td>Cerinš</td>
          <td>34</td>
          <td>10</td>
        </tr>
      </table>

  </div>

</div>

</div>
<div class="sponsors-column">
        <div class="sponsorLogo">
            <div class="sponsor-text">Swedbank</div>
            <div class="logoSponsor">
                    <img class="logoimg" src="/assets/swedbank_og.png">
        </div>
        </div>
        <div class="sponsorLogo">
            <div class="sponsor-text">AOC</div>
            <div class="logoSponsor">
                    <img class="logoimg" src="/assets/aoc.png">
        </div>
    </div>
        <div class="sponsorLogo">
            <div class="sponsor-text">Mantinga</div>
            <div class="logoSponsor">
                    <img class="logoimg" src="/assets/mantinga.png">
        </div>
    </div>
    <div class="sponsorLogo">
        <div class="sponsor-text">Asus</div>
        <div class="logoSponsor">
                <img  class="logoimg" src="/assets/asus.png">
    </div>
</div>
    </div>
    </div>

    <footer class="footer">
        <div>
            Follow us:
        </div>
        <div class="logorow">
            <div class="logocolumn">
                <div class="logo">

                   <a href="#" >
                    <img src="./assets/fb.png">
                   </a> 
                </div>
            </div>
            <div class="logocolumn">
                <div class="logo">
                  <a href="#" >
                    <img src="/assets/iglogo.png">
                  </a> 
                </div>
            </div>
            <div class="logocolumn">
                <div class="logo">
                  <a href="#" >
                        <img src="/assets/email.png">
                      </a> 
            </div>
        </div>
        </div>
    </footer>
</body>

app/views/index/contacts.html.erb
<head>
            <%= stylesheet_link_tag 'contacts','layout',  :media => "all" %>
</head>

<body>
    <header>Lietuvos Motokroso Sporto Federacija</header>


    <nav class="Navigation">
        <a href="home.html"> Main</a>
        <a href="contacts.html"> Contacts</a>
        <a href="gallery.html"> Gallery</a>
        <a href="competition.html"> Competition</a>
    </nav>

    <div class="container">
   
       

      
    <div class="row">
        <div class="column">
           
            <div class="text">
                Jeigu turite klausimų susijusių su registracija į varžybas, grupių paskirstymu, artėjančių varžybų
                grafiku užduokite klausimą naudojantis forma dešinėje
            </div>
            <div class="image">
                <img class="image" src="/assets/partbackground2.jpg">
            </div>


        </div>
        <div class="column">

            <label>First Name</label>
            <input type="text" placeholder="Your name">
            <label>Second Name</label>
            <input type="text" placeholder="Your surname">
            <label>Your Email</label>
            <input type="text" placeholder="Your email">
            <label>Question</label>
            <textarea class="textarea" placeholder="Write something here..."></textarea>
            <input type="submit" value="Send Form" name="submit">
        </div>
    </div>
  <div class="sponsors-column">
        <div class="sponsorLogo">
            <div class="sponsor-text">Swedbank</div>
            <div class="logoSponsor">
                    <img class="logoimg" src="/assets/swedbank_og.png">
        </div>
        </div>
        <div class="sponsorLogo">
            <div class="sponsor-text">AOC</div>
            <div class="logoSponsor">
                    <img class="logoimg" src="/assets/aoc.png">
        </div>
    </div>
        <div class="sponsorLogo">
            <div class="sponsor-text">Mantinga</div>
            <div class="logoSponsor">
                    <img class="logoimg" src="/assets/mantinga.png">
        </div>
    </div>
    <div class="sponsorLogo">
        <div class="sponsor-text">Asus</div>
        <div class="logoSponsor">
                <img  class="logoimg" src="/assets/asus.png">
    </div>
</div>
    </div>
    </div>

    <footer class="footer">
        <div>
            Follow us:
        </div>
        <div class="logorow">
            <div class="logocolumn">
                <div class="logo">

                   <a href="#" >
                    <img src="./assets/fb.png">
                   </a> 
                </div>
            </div>
            <div class="logocolumn">
                <div class="logo">
                  <a href="#" >
                    <img src="/assets/iglogo.png">
                  </a> 
                </div>
            </div>
            <div class="logocolumn">
                <div class="logo">
                  <a href="#" >
                        <img src="/assets/email.png">
                      </a> 
            </div>
        </div>
        </div>
    </footer>
</body>

app/views/index/gallery.html.erb
<head>
<%= stylesheet_link_tag 'gallery','layout', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
    <header>Lietuvos Motokroso Sporto Federacija</header>


    <nav class="Navigation"> 
        <a href="home.html"> Main</a>
        <a href="contacts.html"> Contacts</a> 
        <a href="gallery.html"> Gallery</a>
        <a href="competition.html"> Competition</a>
    </nav>
<div class="aside">
 
  

    <div class="row">
        <div class="column">
            <div class="text">
                Nuotraukos iš 2020m. Rugsėjo 18d. vykusių varžybų Kaune.
                "Cross county 2020" I-ojo etapo
                
            </div>
        </div>

        <div class="column">
            <div class="container2">
                <img src="/assets/1.jpg">
                <img src="/assets/2.jpg">
                <img src="/assets/3.jpg">
                <img src="/assets/4.jpg">
                <img src="/assets/5.jpg">
                <img src="/assets/6.jpg">
                <img src="/assets/7.jpg">
                <img src="/assets/8.jpg">
                <img src="/assets/9.jpg">

            </div>
        </div>

    </div>
    <div class="row">
        <div class="column">
            <div class="text">
                Nuotraukos iš 2020m. Rugsėjo 19d. vykusių varžybų Alytuje.
                "Lietuvos Taurė 2020" etapo 
                
            </div>
        </div>

        <div class="column">
            <div class="container2">
                <img src="/assets/1.jpg">
                <img src="/assets/2.jpg">
                <img src="/assets/3.jpg">
                <img src="/assets/4.jpg">
                <img src="/assets/5.jpg">
                <img src="/assets/6.jpg">
                <img src="/assets/7.jpg">
                <img src="/assets/8.jpg">
                <img src="/assets/9.jpg">

            </div>
        </div>

     </div>
    <div class="sponsors-column">
        <div class="sponsorLogo">
            <div class="sponsor-text">Swedbank</div>
            <div class="logoSponsor">
                    <img class="logoimg" src="/assets/swedbank_og.png">
        </div>
        </div>
        <div class="sponsorLogo">
            <div class="sponsor-text">AOC</div>
            <div class="logoSponsor">
                    <img class="logoimg" src="/assets/aoc.png">
        </div>
    </div>
        <div class="sponsorLogo">
            <div class="sponsor-text">Mantinga</div>
            <div class="logoSponsor">
                    <img class="logoimg" src="/assets/mantinga.png">
        </div>
    </div>
    <div class="sponsorLogo">
        <div class="sponsor-text">Asus</div>
        <div class="logoSponsor">
                <img  class="logoimg" src="/assets/asus.png">
    </div>
</div>
    </div>
    </div>

    <footer class="footer">
        <div>
            Follow us:
        </div>
        <div class="logorow">
            <div class="logocolumn">
                <div class="logo">

                   <a href="#" >
                    <img src="./assets/fb.png">
                   </a> 
                </div>
            </div>
            <div class="logocolumn">
                <div class="logo">
                  <a href="#" >
                    <img src="/assets/iglogo.png">
                  </a> 
                </div>
            </div>
            <div class="logocolumn">
                <div class="logo">
                  <a href="#" >
                        <img src="/assets/email.png">
                      </a> 
            </div>
        </div>
        </div>
    </footer>
</body>

app/views/index/home.html.erb
<head>
<%= stylesheet_link_tag 'index','layout', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <header>Lietuvos Motokroso Sporto Federacija</header>


    <nav class="Navigation"> 
        <a href="home"> Main</a>
        <a href="contacts.html"> Contacts</a> 
        <a href="gallery.html"> Gallery</a>
        <a href="competition.html"> Competition</a>
        <a href="../advertisments/"> adv</a>
    </nav>

    
<div class="container">
   
   

  
    <div class="content-column">
        <div class="newsCol">
            <div class="container imagetext">
                <img class="image" <%=image_tag("partBackground.jpg")%>/>
                <div class="text">
                    Spalio mėn. 10 d. Zokniuose, Šiaulių r. vyks 2020 m. Lietuvos Cross Country Čempionato ir Taurės V etapas
                    <div>
                        <a id="readMore" href="#">Read more</a>
                    </div>
                </div>
            </div>
        </div>
   
        <div class="newsCol">
            <div class="container imagetext">
                <img class="image" src="/assets/partBackground1.jpg"/>
                <div class="text">
                    Rugsėjo mėn. 27 d. Dubysos slėnio trasoje vyks paskutinis Motokroso varžybų "Lietuvos Taurė 2020" etapas. Po varžybų vyks metiniai apdovanojimai!!!
                    <div>
                        <a id="readMore" href="#">Read more</a>

                    </div>
                </div>
            </div>
            
        </div>
        <div class="newsCol">
            <div class="container imagetext">
                <img class="image" src="/assets/partbackground2.jpg"/>
                <div class="text">
                    Rugsėjo mėn. 19-20 d. Šilutės raj. vyks 2020 m. Lietuvos Enduro Čempionato ir Taurės bei 2020 m. Lietuvos Enduro Sprinto Taurės III-asis etapas
                    <div>
                        <a id="readMore" href="#">Read more</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="newsCol">
            <div class="container imagetext">
                <img class="image" src="/assets/attention.jpg"/>
                <div class="text">
                    DĖMESIO!!! Informuojame, kad motokroso varžybos "Nemuno Taurė 2020", turėjusios vykti rugsėjo mėn. 6 d.Kėdainiuose ATŠAUKIAMOS!
                    <div>
                        <a id="readMore" href="#">Read more</a>
                    </div>
                </div>
            </div>
        </div>
      
    </div>
    <div class="sponsors-column">
        <div class="sponsorLogo">
            <div class="sponsor-text">Swedbank</div>
            <div class="logoSponsor">
                    <img class="logoimg" src="/assets/swedbank_og.png">
        </div>
        </div>
        <div class="sponsorLogo">
            <div class="sponsor-text">AOC</div>
            <div class="logoSponsor">
                    <img class="logoimg" src="/assets/aoc.png">
        </div>
    </div>
        <div class="sponsorLogo">
            <div class="sponsor-text">Mantinga</div>
            <div class="logoSponsor">
                    <img class="logoimg" src="/assets/mantinga.png">
        </div>
    </div>
    <div class="sponsorLogo">
        <div class="sponsor-text">Asus</div>
        <div class="logoSponsor">
                <img  class="logoimg" src="/assets/asus.png">
    </div>
</div>
    </div>
    </div>

    <footer class="footer">
        <div>
            Follow us:
        </div>
        <div class="logorow">
            <div class="logocolumn">
                <div class="logo">

                   <a href="#" >
                    <img src="/assets/fb.png">
                   </a> 
                </div>
            </div>
            <div class="logocolumn">
                <div class="logo">
                  <a href="#" >
                    <img src="/assets/iglogo.png">
                  </a> 
                </div>
            </div>
            <div class="logocolumn">
                <div class="logo">
                  <a href="#" >
                        <img src="/assets/email.png">
                      </a> 
            </div>
        </div>
        </div>
    </footer>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>

    <%# <%= stylesheet_link_tag 'application','layout', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
      <%= csrf_meta_tags %>
  </head>

  <body>
  <% if current_user %>
  Signed in as <%= current_user.username %> | <button><%= link_to "Logout", '/logout' %></button>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/users/new' %>
<% end %>
    <%= yield %>
    
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<style>
@import url(https://fonts.googleapis.com/css?family=Roboto:300);
.login-page {
  width: 360px;
  padding: 8% 0 0;
  margin: auto;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 100px;
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 15px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #4CAF50;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.form button:hover,.form button:active,.form button:focus {
  background: #43A047;
}
.form .message {
  margin: 15px 0 0;
  color: #b3b3b3;
  font-size: 12px;
}
.form .message a {
  color: #4CAF50;
  text-decoration: none;
}
.form .register-form {
  display: none;
}
.container {
  position: relative;
  z-index: 1;
  max-width: 300px;
  margin: 0 auto;
}
.container:before, .container:after {
  content: "";
  display: block;
  clear: both;
}
.container .info {
  margin: 50px auto;
  text-align: center;
}
.container .info h1 {
  margin: 0 0 15px;
  padding: 0;
  font-size: 36px;
  font-weight: 300;
  color: #1a1a1a;
}
.container .info span {
  color: #4d4d4d;
  font-size: 12px;
}
.container .info span a {
  color: #000000;
  text-decoration: none;
}
.container .info span .fa {
  color: #EF3B3A;
}
body {
  background: #76b852; /* fallback for old browsers */
  background: -webkit-linear-gradient(right, #76b852, #8DC26F);
  background: -moz-linear-gradient(right, #76b852, #8DC26F);
  background: -o-linear-gradient(right, #76b852, #8DC26F);
  background: linear-gradient(to left, #76b852, #8DC26F);
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;      
}
</style>

<%= form_for @user do |f|%> 
 <div class="login-page">

  <div class="form">
   <h1>Sign Up</h1>
    <form class="login-form">
       <%= f.text_field :username%><br> 
        <%= f.password_field :password%><br>
        <%= f.submit %>
      <p class="message">Already registered? <a href="#">Login!</a></p>
    </form>
  </div>
</div>
<%end%>